checksumBehavior: ignore

enableGlobalCache: false

enableImmutableInstalls: false

enableMirror: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

npmScopes:
  storybook:
    npmRegistryServer: "http://localhost:6001/"

pnpFallbackMode: none

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.5.1.cjs
